/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration for creating a machine. */
export interface MachineConfig {
  /** Unique machine name. Used as the VM identifier. */
  name: string
  /** Host directories to mount into the VM. */
  mounts?: Array<HostMountConfig>
  /** Port mappings from host to guest. */
  ports?: Array<PortMappingConfig>
  /** VM resource allocation. */
  resources?: VmResourcesConfig
  /** If true, the DB record is kept as a persistent machine. */
  persistent?: boolean
}
/** A host directory mount specification. */
export interface HostMountConfig {
  /** Absolute path on the host. */
  source: string
  /** Absolute path inside the guest. */
  target: string
  /** Mount as read-only (default: true). */
  readOnly?: boolean
}
/** A port mapping from host to guest. */
export interface PortMappingConfig {
  /** Port on the host. */
  host: number
  /** Port inside the guest. */
  guest: number
}
/** VM resource allocation. */
export interface VmResourcesConfig {
  /** Number of vCPUs (default: src/data/resources.rs default). */
  cpus?: number
  /** Memory in MiB (default: src/data/resources.rs default). */
  memoryMib?: number
  /** Enable outbound network access (default: false). */
  network?: boolean
  /** Storage disk size in GiB (default: 20). */
  storageGib?: number
  /** Overlay disk size in GiB (default: 10). */
  overlayGib?: number
  /** Enable GPU acceleration (virtio-gpu/venus). Local target only (default: false). */
  gpu?: boolean
  /** GPU VRAM in MiB (default: engine default when GPU is enabled). */
  gpuVramMib?: number
}
/** Options for executing a command. */
export interface ExecOptions {
  /** Environment variables as key-value pairs. */
  env?: Array<EnvVar>
  /** Working directory inside the VM/container. */
  workdir?: string
  /** Timeout in seconds. */
  timeoutSecs?: number
}
/** Options for writing a file into the VM. */
export interface FileWriteOptions {
  /** Optional octal file mode (for example, 0o644). */
  mode?: number
}
/** An environment variable key-value pair. */
export interface EnvVar {
  key: string
  value: string
}
/** Result of executing a command. */
export interface ExecResult {
  /** Process exit code. */
  exitCode: number
  /** Standard output. */
  stdout: string
  /** Standard error. */
  stderr: string
}
/** Information about a pulled/cached OCI image. */
export interface ImageInfo {
  /** Image reference (e.g., "alpine:latest"). */
  reference: string
  /** Image digest (sha256:...). */
  digest: string
  /** Image size in bytes. */
  size: number
  /** Platform architecture (e.g., "arm64"). */
  architecture: string
  /** Platform OS (e.g., "linux"). */
  os: string
}
/** Event from a streaming exec session. */
export interface ExecStreamEvent {
  /** Event kind: stdout, stderr, exit, or error. */
  kind: string
  /** Text payload for stdout/stderr events. */
  data?: string
  /** Exit code for exit events. */
  exitCode?: number
  /** Error message for error events. */
  message?: string
}
export declare class NapiMachine {
  /** Create a new machine. Does not start the VM yet — call `start()`. */
  constructor(config: MachineConfig)
  /**
   * Attach to an existing machine by name, starting it if stopped
   * (start-or-reconnect). Lets a persisted machine be re-opened in a new
   * process — backs the SDK's local `Machine.connect()`.
   */
  static connect(name: string): NapiMachine
  /** Get the machine name. */
  get name(): string
  /**
   * Start a command and return a live `ExecStream` of its output events. A
   * worker thread drives the engine's `exec_streaming_with` and feeds an mpsc
   * channel the stream drains incrementally (no buffering).
   */
  execStream(command: Array<string>, options?: ExecOptions | undefined | null): ExecStream
  /** Get the child PID if the VM is running. */
  get pid(): number | null
  /** Check if the VM process is currently running. */
  get isRunning(): boolean
  /** Get the current machine state: "stopped", "starting", "running", or "stopping". */
  state(): string
  /**
   * Start the machine VM. Boots via fork + libkrun, waits for agent ready,
   * then connects the vsock client.
   */
  start(): Promise<void>
  /**
   * Start this machine as a forkable fork base (memfd-backed guest RAM +
   * control socket) so it can later be `fork()`-ed.
   */
  startForkable(): Promise<void>
  /**
   * Fork this running, forkable machine into a new clone via copy-on-write
   * live RAM + disks (same host). `ports` are `{ host, guest }` inbound
   * forwards for the clone. Returns a handle to the running clone.
   */
  fork(name: string, ports?: Array<PortMappingConfig> | undefined | null): Promise<NapiMachine>
  /** Execute a command directly in the VM (not in a container). */
  exec(command: Array<string>, options?: ExecOptions | undefined | null): Promise<ExecResult>
  /**
   * Pull an OCI image and run a command inside it.
   *
   * This pulls the image (if not already cached), creates an overlay rootfs,
   * runs the command inside it, and cleans up. Equivalent to `smolvm run`.
   */
  run(image: string, command: Array<string>, options?: ExecOptions | undefined | null): Promise<ExecResult>
  /** Pull an OCI image into the machine's storage. */
  pullImage(image: string): Promise<ImageInfo>
  /** List all cached OCI images in the machine's storage. */
  listImages(): Promise<Array<ImageInfo>>
  /** Write a file into the running VM. */
  writeFile(path: string, data: Buffer, options?: FileWriteOptions | undefined | null): Promise<void>
  /** Read a file from the running VM. */
  readFile(path: string): Promise<Buffer>
  /** Execute a command and return streaming stdout/stderr/exit events. */
  execStreaming(command: Array<string>, options?: ExecOptions | undefined | null): Promise<Array<ExecStreamEvent>>
  /** Stop the machine VM gracefully. */
  stop(): Promise<void>
  /** Stop the machine and clean up all storage (disks, config). */
  delete(): Promise<void>
}
/**
 * A live, incremental exec stream. `next()` resolves with the next event as it
 * arrives (off the libuv loop via spawn_blocking), or `null` once the command
 * exits and the channel closes. Mirrors the Python SDK's ExecStream iterator.
 */
export declare class ExecStream {
  next(): Promise<ExecStreamEvent | null>
}
